# Generated by Django 2.2.5 on 2019-12-02 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('direccion', models.TextField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('capacidad', models.IntegerField()),
                ('etiqueta', models.ManyToManyField(to='Organizer.Etiqueta')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField()),
                ('asistencia_activa', models.BooleanField()),
                ('qr', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.Evento')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.Evento')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidaInvitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.Invitacion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizer.Staff')),
            ],
            options={
                'unique_together': {('user_id', 'invitacion_id')},
            },
        ),
    ]
