# Generated by Django 2.2.5 on 2019-12-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
