# Generated by Django 2.2.5 on 2019-10-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
