# Generated by Django 2.2.6 on 2019-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
