# Generated by Django 2.2.5 on 2019-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=42)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=75)),
                ('user', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('password', models.CharField(max_length=100)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
    ]
