# Generated by Django 2.2.5 on 2019-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='organizador',
            new_name='es_Organizador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_Staff',
            field=models.BooleanField(default=False),
        ),
    ]
