# Generated by Django 2.2.5 on 2019-11-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='organizador',
        ),
    ]
